export { default as CopyIcon } from './assets/copy.svg?react';
export { default as MarkdownIcon } from './assets/markdown.svg?react';
export { default as DownloadIcon } from './assets/download.svg?react';
export { default as OpenIcon } from './assets/open.svg?react';
export { default as RecoveryIcon } from './assets/recovery.svg?react';
export { default as InfoIcon } from './assets/info.svg?react';
export { default as PrintIcon } from './assets/print.svg?react';
export { default as PDFIcon } from './assets/pdf.svg?react';
export { default as AnswerIcon } from './assets/answer.svg?react';
