name: Deploy React to gh-pages with staging branch

on:
  workflow_dispatch:
    inputs:
      stagingBranch:
        description: 'Staging Branch'
        default: 'rewrite'

jobs:
  build:
    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        branch:
          - main
          - '${{ github.event.inputs.stagingBranch }}'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      
      - run: npm ci
      
      - name: Build app
        run: npm run build
      
      - uses: actions/upload-artifact@v3
        if: matrix.branch == 'main'
        with:
          path: build/*
          name: build-${{matrix.branch}}

      - uses: actions/upload-artifact@v3
        if: matrix.branch != 'main'
        with:
          path: dist/*
          name: build-${{matrix.branch}}
  
  assemble:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name: Download main build
        uses: actions/download-artifact@v3
        with:
          name: build-main
          path: build
      
      - name: Download staging build
        uses: actions/download-artifact@v3
        with:
          name: build-${{github.event.inputs.stagingBranch}}
          path: build/staging

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          # Path of the directory containing the static assets.
          path: build
  
  deploy:
    runs-on: ubuntu-latest
    needs: assemble

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
